// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvHxLu3P4D_Al9KwEH5nS4GRttjeQLRI',
    appId: '1:944346392654:web:e29ad1f649daf24a5b3b1f',
    messagingSenderId: '944346392654',
    projectId: 'job-finding-68663',
    authDomain: 'job-finding-68663.firebaseapp.com',
    storageBucket: 'job-finding-68663.appspot.com',
    measurementId: 'G-P8JM1NKQBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaWpKNtYYZ9qCnISxlJOVJFtcioTj5P6U',
    appId: '1:944346392654:android:b7e23ae1ac49a6ba5b3b1f',
    messagingSenderId: '944346392654',
    projectId: 'job-finding-68663',
    storageBucket: 'job-finding-68663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4OeMYPr5h2CvBxuHh-u3hMsbZ8IupgM',
    appId: '1:944346392654:ios:910c356e59224dbf5b3b1f',
    messagingSenderId: '944346392654',
    projectId: 'job-finding-68663',
    storageBucket: 'job-finding-68663.appspot.com',
    iosBundleId: 'com.example.jobRecuter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4OeMYPr5h2CvBxuHh-u3hMsbZ8IupgM',
    appId: '1:944346392654:ios:910c356e59224dbf5b3b1f',
    messagingSenderId: '944346392654',
    projectId: 'job-finding-68663',
    storageBucket: 'job-finding-68663.appspot.com',
    iosBundleId: 'com.example.jobRecuter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvHxLu3P4D_Al9KwEH5nS4GRttjeQLRI',
    appId: '1:944346392654:web:771df4aaefae80d45b3b1f',
    messagingSenderId: '944346392654',
    projectId: 'job-finding-68663',
    authDomain: 'job-finding-68663.firebaseapp.com',
    storageBucket: 'job-finding-68663.appspot.com',
    measurementId: 'G-5W1KYRVM48',
  );
}
